
;Programa que transforma um n�mero decimal
;a bin�rio
; IF apenas de teste
TESTE: EQU 1
SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
L1: DIV DOIS ;4
STORE  NEW_DATA
MULT DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA, OLD_DATA
LOAD OLD_DATA
IF TESTE
STOP
JMPP L1
STOP
SECTION DATA
DOIS: CONST 2 ;28
IF TESTE
TESTELABEL: SPACE 2
IF TESTE
TRES: CONST 3
OLD_DATA: SPACE ;29
NEW_DATA: SPACE ;30
TMP_DATA: SPACE ;31
